name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

env:
  IMAGE_NAME: nodejs-demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start container for testing
        run: |
          docker run -d -p 3000:3000 --name app-container ${{ env.IMAGE_NAME }}:latest
          # Wait for container to fully start
          sleep 5
      
      - name: Test with curl
        run: |
          response=$(curl -s http://localhost:3000)
          echo "Response: $response"
          
          # Check if the response contains expected text
          if [[ "$response" == *"Hello from nodejs-demo-app"* ]]; then
            echo "Test passed! Application is working as expected."
          else
            echo "Test failed! Application response doesn't match expected output."
            exit 1
          fi
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max